[project]
name = "StarCalculator"
version = "0.1.0"
description = "Calculate the position of a star(s)"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
starcalculator = "starcalculator.main:main"